### PR TITLE
[Context] Replace actions by actions(promoted) on front page

### PR DESCRIPTION
**Pull request by FrClem**
Tested locally on #foescot

### CODE REVIEW

**Comment by torotil** [comment]
Where is the actions_promoted view defined? I guess it needs to be added to campaignion_views as well, right?

**Comment by FrClem** [comment]
@torotil I think that this is now more complete: both the "actions" and the "promoted actions" views include the flexible forms. 
The actions_promoted view is linked in the campaignion_views/campaignion_views.info and defined in the campaignion_views/campaignion_views.views_default.inc file

**Comment by katzmo** [comment]
I'm not sure about having flexible forms in the "actions" view because that does significantly change the current functionality and is likely to effect live sites? ("actions promoted" is fine IMO as you have to manually promote your actions to make them show up)

**Comment by torotil** [comment]
As discussed with Clemence: “actions (promoted)” could be changed to simply join to the webform table then there is no need to filter by node-type which makes this more generic.

**Comment by FrClem** [comment]
@torotil the node type filter --> webform join is already updated in this branch

**Review by torotil — APPROVED** [review]

**Comment by torotil** [comment]
Can you update https://github.com/moreonion/campaignion_starterkit/pull/76 too? Then I can merge both.

**Pull request merged**
